name:  start workers
on:
  issues:
    types: labeled
  schedule:
    - cron: 12 8 * * *
jobs:
 StartWorks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:  
    - uses: actions/checkout@v2
      with:
       ref: dev
       path: dev
    - id: list_dirs
      run: echo "::set-output name=matrix::$(ls dev/query/java_*.ql|jq -cnR '[inputs | select(length>0)]')"

 ManyWorks:
    runs-on: ubuntu-latest
    needs: StartWorks
    strategy:
      fail-fast: false
      matrix:
        job: ${{fromJson(needs.StartWorks.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
      with:
       ref: dev
       path: dev
    - name: start $JOB
      run: |
          sudo python3 ./dev/code/myworkerUpd.py $JOB ./dev/list/java_listHashOutList java ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ secrets.ARCHIVEPASSWORD }} ${{ secrets.ARCHIVEURL }}
      env:
        JOB: ${{ matrix.job }}
